### ISSUE TITLE
Request: Feature where you can export multiple channel WAV files at once.

### ISSUE THREAD

**Issue by pr0t0gam3r** [bbbradsmith/nsfplay#73] opened 2023-04-02 20:59 UTC
I usually use NSFPlay to export the channel wav audio files for my oscilloscope videos, but there is one thing that bothers me. I have to go into the channel mask settings and solo a channel, then export the wav file for it. And I have to do this for all other channels + exporting the wav with all the channels at once. This can really be a hassle if one song uses, let's say 8 channels. I know I might be complaining for no reason, but this is basically an issue and request. Can it be added to the next NSFPlay version?

**Comment by 0x5066** [comment] 2023-04-02 21:37
Duplicate of #72 and #11

**Comment by bbbradsmith** [comment] 2023-04-02 21:46
Yes, it's on the roadmap for version 3.

**Closed by bbbradsmith** 2023-04-02 21:46 UTC
